# Generated by Django 5.0.6 on 2024-07-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='disponibles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='disponibles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peluches',
            name='disponibles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
