# Generated by Django 5.0.6 on 2024-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_cartas_disponibles_juegos_de_mesa_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='en_stock',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartas',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='en_stock',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
