# Generated by Django 5.0.6 on 2024-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_figura_de_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('disponibles', models.IntegerField()),
                ('en_stock', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Autito',
                'verbose_name_plural': 'Autitos',
                'ordering': ['precio'],
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='cartas',
            options={'ordering': ['precio'], 'verbose_name': 'Juego de Cartas', 'verbose_name_plural': 'Juegos de Cartas'},
        ),
        migrations.AlterModelOptions(
            name='figura_de_accion',
            options={'ordering': ['precio'], 'verbose_name': 'Figura de Acción', 'verbose_name_plural': 'Figuras de Acción'},
        ),
        migrations.AlterModelOptions(
            name='juegos_de_mesa',
            options={'ordering': ['precio'], 'verbose_name': 'Juego de Mesa', 'verbose_name_plural': 'Juegos de Mesa'},
        ),
        migrations.AlterModelOptions(
            name='peluches',
            options={'ordering': ['precio'], 'verbose_name': 'Peluche', 'verbose_name_plural': 'Peluches'},
        ),
    ]
