# Generated by Django 5.0.6 on 2024-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_autitos_delete_cliente_alter_cartas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluches',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
