# Generated by Django 5.0.6 on 2024-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_avatar_delete_autitos_alter_peluches_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluches',
            name='foto',
            field=models.ImageField(upload_to='Peluches/'),
        ),
    ]
