# Generated by Django 5.0.6 on 2024-07-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_peluches_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluches',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='media/Peluches/'),
        ),
    ]
