# Generated by Django 5.0.6 on 2024-07-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_peluches_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='foto',
            field=models.ImageField(default='default_Models.png', upload_to='media/Cartas/'),
        ),
        migrations.AddField(
            model_name='figura_de_accion',
            name='foto',
            field=models.ImageField(default='default_Models.png', upload_to='media/Peluches/'),
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='foto',
            field=models.ImageField(default='default_Models.png', upload_to='media/Peluches/'),
        ),
        migrations.AlterField(
            model_name='peluches',
            name='foto',
            field=models.ImageField(default='default_Models.png', upload_to='media/Peluches/'),
        ),
    ]
