# Generated by Django 5.0.6 on 2024-07-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_cartas_foto_figura_de_accion_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura_de_accion',
            name='foto',
            field=models.ImageField(default='default_Models.png', upload_to='media/Figuras/'),
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='foto',
            field=models.ImageField(default='default_Models.png', upload_to='media/Mesa/'),
        ),
    ]
