# Generated by Django 5.0.6 on 2024-07-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_figura_de_accion_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='avatar'),
        ),
    ]
